name: Verify Renovate config

on: push

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate
        uses: rinchsan/renovate-config-validator@v0.0.11
        with:
          pattern: '*.json' # Regular expression for filename to validate, default to *.json